[package]
name = "temper-game-systems"
edition.workspace = true
version.workspace = true

[dependencies]
background = { path = "./src/background" }
mobs = { path = "./src/mobs" }
pathfinding = { path = "./src/pathfinding" }
packets = { path = "./src/packets" }
physics = { path = "./src/physics" }
player = { path = "./src/player" }
shutdown = { path = "./src/shutdown" }
world = { path = "./src/world" }
interactions = { path = "./src/interactions" }
tempfile = { workspace = true }
bevy_ecs = { workspace = true }
temper-command-infra = { workspace = true }
temper-config = { workspace = true }
temper-scheduler = { workspace = true }
temper-state = { workspace = true }
temper-data = { workspace = true }

[dev-dependencies]
bevy_math = { workspace = true }
temper-components = { workspace = true }
temper-core = { workspace = true }
temper-entities = { workspace = true }
temper-macros = { workspace = true }
temper-messages = { workspace = true }
temper-resources = { workspace = true }
temper-state = { workspace = true }
temper-world = { workspace = true }
temper-world-format = { workspace = true }

[lints]
workspace = true
