[package]
name = "temper-data"
version = "0.1.0"
edition = "2021"
build = "build/build.rs"

[build-dependencies]
heck = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
rayon = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
syn = { workspace = true }

[lints]
workspace = true

[lib]
doctest = false
